# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
  - master

resources:
  - repo: self

variables:
  image: "patnaikshekhar/xplatbuild"
  tag: "$(Build.BuildId)"
  platform: "linux/arm64,linux/amd64"

stages:
  - stage: Build
    displayName: Build cross platform images
    jobs:
      - job: Build
        displayName: Build
        pool:
          vmImage: "ubuntu-latest"
        steps:
          - task: Bash@3
            displayName: Install Docker CE
            inputs:
              targetType: "inline"
              script: |
                sudo apt-get -y update
                sudo apt-get -y install \
                  apt-transport-https \
                  ca-certificates \
                  curl \
                  make \
                  software-properties-common
                curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
                sudo apt-key fingerprint 0EBFCD88
                sudo add-apt-repository \
                  "deb [arch=amd64] https://download.docker.com/linux/ubuntu \
                  xenial \
                  edge"
                sudo apt-get -y update
                sudo apt-get -y install docker-ce
          - task: Bash@3
            displayName: Install QEMU and register binfmt
            inputs:
              targetType: "inline"
              script: |
                docker run --privileged linuxkit/binfmt:v0.8
          - task: Bash@3
            displayName: Build image for multiple platforms
            inputs:
              targetType: "inline"
              script: |
                export DOCKER_CLI_EXPERIMENTAL=enabled
                docker buildx create --use --name xplatbuilder
                docker buildx build -t $(image):$(tag) --platform $(platform) --output=type=docker ./sample

          # - task: Docker@2
          #   displayName: Install QEMU and register binfmt
          #   inputs:
          #     command: run
          #     arguments: "--privileged linuxkit/binfmt:v0.7"
          # - task: Docker@2
          #   displayName: Create a builder
          #   inputs:
          #     command: buildx
          #     arguments: "create --use --name xplatbuilder"
          # - task: Docker@2
          #   displayName: Build image for multiple platforms
          #   inputs:
          #     command: buildx
          #     arguments: "build -t $(image):$(tag) --platform $(platform) --output=type=docker ./sample"
          # - task: Docker@2
          #   displayName: Login to Dockerhub
          #   inputs:
          #     containerRegistry: "PersonalDockerHub"
          #     command: "login"
