# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
  - master

resources:
  - repo: self

variables:
  image: "patnaikshekhar/xplatbuild"
  tag: "$(Build.BuildId)"
  platform: "linux/arm64,linux/amd64"

stages:
  - stage: Build
    displayName: Build cross platform images
    jobs:
      - job: Build
        displayName: Build
        pool:
          vmImage: "ubuntu-latest"
        steps:
          - task: Bash@3
            inputs:
              targetType: "inline"
              script: "export DOCKER_CLI_EXPERIMENTAL=enabled"
          - task: Docker@2
            displayName: Install QEMU
            inputs:
              command: run
              arguments: "--privileged linuxkit/binfmt:v0.7"
          - task: Docker@2
            displayName: Create a builder
            inputs:
              command: buildx
              arguments: "create --use --platform ${platform} --name xplatbuilder"
          - task: Docker@2
            displayName: Build image for multiple platforms
            inputs:
              command: buildx build
              arguments: "--tag ${image}:${tag} --push ./sample"
